USE ecommerce;
SHOW TABLES;
SELECT * FROM orders;
SELECT * FROM orders WHERE Paymentmethod = 'Online';
SELECT * FROM orders ORDER BY Unitprice DESC;
SELECT Product, COUNT(*) AS TotalOrders FROM orders GROUP BY Product;
SELECT SUM(Quantity) AS TotalQuantity FROM orders;
SELECT AVG(UnitPrice) AS AveragePrice FROM orders;
SELECT PaymentMethod, COUNT(*) AS TotalOrders FROM orders GROUP BY PaymentMethod;
SELECT OrderStatus, COUNT(*) AS TotalOrders FROM orders GROUP BY OrderStatus;